from enum import Enum

NAME_SECTION_DELIMINATOR    = "|"
SECTION_DATA_DELIMINATOR    = ";"
SUBSECTION_DATA_DELIMINATOR = ":"
DATA_LIST_DELIMINATOR       = ","
ESCAPED_DELIMINATORS = [SECTION_DATA_DELIMINATOR, DATA_LIST_DELIMINATOR, NAME_SECTION_DELIMINATOR]

class OpCode(Enum):
    EXTRUSION = "EXT"
    DRESSUP = "DRE"
    SKETCH = "SKT"
    REFINE = "RFI"
    BOOLEAN = "BOL"
    THICKNESS = "THK"
    COMPOUND = "CMP"